### ISSUE TITLE
Cannot validate when copy and paste a knex query

### ISSUE THREAD

**Issue by ShanChathusanda93** [michaelavila/knex-querylab#4]
I have tried to **copy** and **paste** a knex query which is working correctly in my application to the provided validator. But it doesn't validate the query.

**Comment by michaelavila** [comment]
@ShanChathusanda93 do you have an example query I can reproduce the problem with? I haven't updated the knex dependency for this in a very long time. I can do that and test your query if you can send me something I can run to see it break. Thanks!

**Comment by ShanChathusanda93** [comment]
You can try a simple knex query for this context. 
Ex : knex.select('a','b').from('table_c');
Copy this knex query into the validator at http://michaelavila.com/knex-querylab/ and you can see that this query isn't validated. But when typing it from the beginning (the same query) it is validated. This is the problem with the validator.

**Comment by michaelavila** [comment]
@ShanChathusanda93 Thanks!

The query you sent me does work when I copy/paste. Here's a screenshot:

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/100039/60456059-08e09080-9bed-11e9-9bc0-76a102b9679b.png">

Could it be the case that the place your copy/pasting from is including extra special characters that the knex system does not understand?

**Comment by ShanChathusanda93** [comment]
Here's mine.
![image](https://user-images.githubusercontent.com/19262008/60497833-37389b80-9cd3-11e9-97aa-cee144d2c04a.png)
I just copy the query from my comment and paste it.

**Comment by michaelavila** [comment]
@ShanChathusanda93 looks like it's producing the right output, but it's just greyed out. Is that true?

What operating system are you running? What browser are you looking at this in?

**Comment by ShanChathusanda93** [comment]
Yes. You are right. It is greyed. But when we type it from the beginning it is not displayed in grey. Isn't it. So I think this **grey** thing makes users uncomfortable. I am using Ubuntu 18.04 as my OS and Chrome is the browser.

**Comment by ShanChathusanda93** [comment]
This output is from firefox browser.
![image](https://user-images.githubusercontent.com/19262008/60560565-e924a600-9d6d-11e9-8672-59d8d1495d6b.png)
Above image contains the result when we write the query from the beginning.
![image](https://user-images.githubusercontent.com/19262008/60560658-428cd500-9d6e-11e9-9459-ab35e96db4e0.png)
This image contains the result when we copy and paste a query.

**Comment by michaelavila** [comment]
@ShanChathusanda93 I'm going to take a look at this over the weekend and see if there's an alternative way of doing this that doesn't introduce that weird behavior

**Comment by ShanChathusanda93** [comment]
@michaelavila sounds great.

**Comment by michaelavila** [comment]
@ShanChathusanda93 let me know if the updated system behaves better for you

**Comment by ShanChathusanda93** [comment]
@michaelavila Thanks for the updated version of the validator. Now the validator works greater than the previous version. Thanks again. Also, please make sure that it supports for all versions of knex. Because some parametarized queries are not validated correctly.

**Comment by michaelavila** [comment]
@ShanChathusanda93 thanks for checking and reporting back.

> Also, please make sure that it supports for all versions of knex. Because some parametarized queries are not validated correctly.

Can you file an issue with what is happening specifically?
