### ISSUE TITLE
Use `toSQL` instead of `toQuery`

### ISSUE THREAD

**Issue by peey** [michaelavila/knex-querylab#5]
https://github.com/michaelavila/knex-querylab/blob/87d5ff59387bd298b5faae4f8fa31e3804830356/src/App.tsx#L34

I think `toQuery` might have some limitations, e.g. see [this comment](https://github.com/knex/knex/issues/3123#issuecomment-478260219)

**Comment by michaelavila** [comment]
I switched over to `toSQL().sql`, let me know if that's behaving better for you.

**Comment by peey** [comment]
@michaelavila I think `toSQL().toNative()` might work better than `toSQL().sql`.

This also introduces another problem: bindings are no longer a part of the query but showed as separate objects. 

I realized today that knex can't actually show the final query sent to DB, it can either (a) show the query and bindings that it'll send as arguments to the driver, or (b) try to "approximate" what the driver might do with bindings (which is what `toQuery` does, but it produces the wrong query in some edge cases). 

If you show the query and bindings then the tool works in 100% of cases but may become less useful for 90% of the cases (you can no longer just directly copy paste the query with data and run it in SQL). If you show `toQuery` then tool remains useful for 90% of cases but breaks unexpectedly in 10%.

Looks like there is no clean way out of this.

**Comment by michaelavila** [comment]
@peey Yeah, I noticed this last night. I have a thing I'm trying, I'll put up a new version today or tomorrow. My plan is to just show both. I'll show the result of `toQuery()` where it was before, and below that I'll show a breakdown using `toSQL().toNative()`.

**Comment by michaelavila** [comment]
@peey it's still a work in progress, but here is a first pass that includes the toSQL().toNative():

https://michaelavila.com/knex-querylab

I added a few things:

- you can now copy/paste the URL and share queries (the query isn't saved anywhere, just put into the query string)
- it now shows toQuery as well as toSQL().toNative
- it shows the bindings as a simple list
- I put in some syntax highlighting for the js/sql

**Comment by peey** [comment]
This looks absolutely wonderful! Thanks for all your work, you've added more things than this issue asked for!

A couple of notes:

1. The page goes blank with the following query in postgres dialect:
   ```
     knex("recharges").insert({
     value: {
        currency: "USD",
        amount: 200
     }
     })
   ```
   This is the query from: https://github.com/knex/knex/issues/3123 which prompted me to open this issue, so it'd be a good idea to keep this as one of the test cases
2. The "delete the entire query and then paste / write another" UIflow seems to be interrupted by input value for "Expression" being set to "Unknown Error". If you somehow set the "placeholder" instead of "value" for that (which I guess may not be straightforward because it's a `textarea` and not an `input`) then I believe it will no longer interfere with user input.

**Comment by michaelavila** [comment]
@peey Great! Thanks for the feedback. I'll take a look a these today.

**Comment by michaelavila** [comment]
@peey #2 should be resolved now, just pushed a change. #1 I need to spend more time looking into.

**Comment by michaelavila** [comment]
I'm noticing now that copy/paste from the Query and SQL sections doesn't work. I'll add copy to clipboard buttons for each of those boxes.

**Comment by michaelavila** [comment]
@peey 

This is working now:

```javascript
 knex("recharges").insert({
  value: {
     currency: "USD",
     amount: 200
  }
})
```

You should be able to verify here: [QueryLab](https://michaelavila.com/knex-querylab/?query=NYOwpgHgFARATmAxgCwIZwOZgM4wJQB0AliNmHAC5QDeAUAAT0BuqANgK5gBc9dj-idnAQhEATx4wAqgGUAIjAA0DfvVQBbAPbsQFHgCYADIZUBfM3iA)

Right now I'm just `JSON.stringify()` the result, so it's just showing some json as a string. Later this evening I will modify that bindings table to render those objects in a better way.
